Repository freedomofpress/securedrop, pull requests merged in 2018-08, with the labels that each got.

#3679 Bump pyca/cryptography to 2.3 for admin workstation
  admin/requirements-ansible.in
  admin/requirements.txt
Labels: needs QA

#3705 Tor functional test auto generation of instance_information.json
  install_files/ansible-base/roles/app-test/defaults/main.yml
  install_files/ansible-base/roles/app-test/files/tor_app.fact
  install_files/ansible-base/roles/app-test/tasks/extract_apptor_test_config.yml
  install_files/ansible-base/roles/app-test/tasks/main.yml
  install_files/ansible-base/roles/tor-hidden-services/handlers/restart-tor-carefully.yml
  molecule/upgrade/create.yml
  molecule/upgrade/molecule.yml
  molecule/upgrade/playbook.yml
  molecule/upgrade/side_effect.yml
Labels: functional_tests

#3731 Pytest 2 electric boogaloo
  securedrop/tests/conftest.py
  securedrop/tests/test_journalist.py
Labels: goals: app code cleanup, tests, unit_tests

#3741 Update securedrop-app-code dependencies: Flask and Werkzeug
  securedrop/requirements/securedrop-app-code-requirements.in
  securedrop/requirements/securedrop-app-code-requirements.txt
Labels: security
