Repository freedomofpress/securedrop, pull requests merged in 2018-06, with the labels that each got.

#3479 journalist notifications: allow 30 minutes variance in reboot times
  install_files/ansible-base/group_vars/staging.yml
  install_files/ansible-base/roles/app/tasks/setup_cron.yml
  install_files/ansible-base/roles/ossec/files/process_submissions_today.sh
Labels: bug, goals: journalist experience

#3211 Use alembic to version control sqlite database
  .flake8
  docs/development/database_migrations.rst
  docs/index.rst
  install_files/ansible-base/group_vars/all/securedrop
  install_files/ansible-base/roles/app/tasks/create_app_dirs.yml
  install_files/ansible-base/roles/app/tasks/main.yml
  install_files/securedrop-app-code/DEBIAN/control
  install_files/securedrop-app-code/DEBIAN/postinst
  install_files/securedrop-app-code/DEBIAN/postrm
  securedrop/.rsync-filter
  securedrop/Dockerfile
  securedrop/alembic.ini
  securedrop/alembic/env.py
  securedrop/alembic/script.py.mako
  securedrop/alembic/versions/15ac9509fc68_init.py
  securedrop/alembic/versions/faac8092c123_enable_security_pragmas.py
  securedrop/bin/dev-deps
  securedrop/bin/new-migration
  securedrop/crypto_util.py
  securedrop/manage.py
  securedrop/qa_loader.py
  securedrop/requirements/securedrop-app-code-requirements.in
  securedrop/requirements/securedrop-app-code-requirements.txt
  securedrop/tests/conftest.py
  securedrop/tests/migrations/__init__.py
  securedrop/tests/migrations/helpers.py
  securedrop/tests/migrations/migration_15ac9509fc68.py
  securedrop/tests/migrations/migration_faac8092c123.py
  securedrop/tests/test_alembic.py
  securedrop/tests/test_manage.py
  securedrop/tests/test_qa_loader.py
  testinfra/app-code/test_securedrop_app_code.py
Labels: PR: Pending additional work, ops/deployment

#3504 Add generic kernel troubleshooting/rollback docs
  docs/images/edit-grub-0.8.0.png
  docs/images/grubmenu-0.8.0.png
  docs/index.rst
  docs/kernel_troubleshooting.rst
Labels: docs

#3509 journalist: ngettext around unread as it may be singular or plural
  securedrop/journalist_templates/_source_row.html
Labels: goals: i18n, goals: journalist experience

#3515 source: s/mouse/cursor/
  securedrop/source_templates/screensaver.html
Labels: goals: improve source experience

#3525 Update issue / PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: goals: improve developer workflow

#3508 better clean up of files in on removal/purge
  install_files/securedrop-app-code/DEBIAN/postrm
Labels: ops/deployment

#3414 Add ssh instructions link to create_admin_account.rst
  docs/create_admin_account.rst
Labels: docs

#3536 fixes the issue template chooser broken issue
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: goals: improve developer workflow

#3538 Edit feedback include
  docs/includes/provide-feedback.txt
Labels: docs

#3537 mailmap: normalize pierwill <mail@pierwill.com>
  .mailmap
Labels: goals: i18n

#3541 docker: get a recent ubuntu:14.04 to avoid performance problems
  securedrop/Dockerfile
Labels: goals: improve developer workflow

#3481 More integration tests for securedrop-admin
  admin/Dockerfile
  admin/requirements-dev.in
  admin/requirements-dev.txt
  admin/tests/test_integration.py
  admin/tox.ini
Labels: tests

#3425 Replace shell=True / sh calls with sh package (Issue #3071)
  securedrop/Makefile
  securedrop/i18n_tool.py
  securedrop/requirements/develop-requirements.in
  securedrop/requirements/securedrop-app-code-requirements.in
  securedrop/requirements/securedrop-app-code-requirements.txt
  securedrop/tests/test_i18n.py
  securedrop/tests/test_i18n_tool.py
  securedrop/tests/test_template_filters.py
Labels: development env, security

#3546 Disable do-release-upgrade OSSEC notification
  install_files/securedrop-config/DEBIAN/postinst
Labels: ops/deployment

#3539 Docs: Edit admin guide
  docs/admin.rst
Labels: docs

#3547 [0.8.0] Backport kernel docs, upgrade guide from #3545
  docs/index.rst
  docs/kernel_troubleshooting.rst
  docs/upgrade/0.7.x_to_0.8.rst
Labels: docs

#3560 Fine-tunes conditional logic in iptables template
  install_files/ansible-base/roles/restrict-direct-access/templates/rules_v4
Labels: QA: Release

#3564 Login throttling should be per-user
  securedrop/models.py
  securedrop/tests/test_journalist.py
Labels: bug, security

#3578 l10n: sync translations (take 2)
  securedrop/translations/ar/LC_MESSAGES/messages.po
  securedrop/translations/hi/LC_MESSAGES/messages.po
  securedrop/translations/nl/LC_MESSAGES/messages.po
  securedrop/translations/ru/LC_MESSAGES/messages.po
  securedrop/translations/sv/LC_MESSAGES/messages.po
  securedrop/translations/tr/LC_MESSAGES/messages.po
Labels: goals: i18n

#3575 docs: update screenshots for 0.8.0
  docs/images/manual/screenshots/journalist-admin_add_user_hotp.png
  docs/images/manual/screenshots/journalist-admin_add_user_totp.png
  docs/images/manual/screenshots/journalist-admin_changes_logo_image.png
  docs/images/manual/screenshots/journalist-admin_index_no_documents.png
  docs/images/manual/screenshots/journalist-admin_interface_index.png
  docs/images/manual/screenshots/journalist-admin_new_user_two_factor_hotp.png
  docs/images/manual/screenshots/journalist-admin_new_user_two_factor_totp.png
  docs/images/manual/screenshots/journalist-admin_ossec_alert_button.png
  docs/images/manual/screenshots/journalist-admin_system_config_page.png
  docs/images/manual/screenshots/journalist-clicks_on_source_and_selects_documents.png
  docs/images/manual/screenshots/journalist-col_flagged.png
  docs/images/manual/screenshots/journalist-col_has_no_key.png
  docs/images/manual/screenshots/journalist-composes_reply.png
  docs/images/manual/screenshots/journalist-edit_account_user.png
  docs/images/manual/screenshots/journalist-index_javascript.png
  docs/images/manual/screenshots/journalist-index_with_text.png
  docs/images/manual/screenshots/source-checks_for_reply.png
  docs/images/manual/screenshots/source-deletes_reply.png
  docs/images/manual/screenshots/source-enter-codename-in-login.png
  docs/images/manual/screenshots/source-flagged.png
  docs/images/manual/screenshots/source-generate.png
  docs/images/manual/screenshots/source-index.png
  docs/images/manual/screenshots/source-logout_flashed_message.png
  docs/images/manual/screenshots/source-lookup.png
  docs/images/manual/screenshots/source-submission_entered_text.png
Labels: docs
