Repository freedomofpress/securedrop, pull requests merged in 2019-04, with the labels that each got.

#4316 Bump version number for remaining Xenial docs, automate future bumps
  docs/upgrade/xenial_backup_install_restore.rst
  docs/upgrade/xenial_prep.rst
  docs/upgrade/xenial_upgrade_in_place.rst
  update_version.sh
Labels: small off-sprint PR

#4318 [0.12.1] Transitions lint container to Debian Stretch
  devops/docker/Dockerfile.linting
Labels: small off-sprint PR

#4311 Update default staging target to Xenial
  install_files/ansible-base/group_vars/all/securedrop
  molecule/libvirt-staging-xenial/ansible-override-vars.yml
  molecule/libvirt-staging/ansible-override-vars.yml
  molecule/virtualbox-staging-xenial/ansible-override-vars.yml
  molecule/virtualbox-staging/ansible-override-vars.yml
Labels: small off-sprint PR

#4302 Recommend workstation backup as step in the install guide
  docs/backup_workstations.rst
  docs/configure_admin_workstation_post_install.rst
Labels: docs, small off-sprint PR

#4326 Backup: fetch tarball with synchronize instead of fetch
  install_files/ansible-base/roles/backup/tasks/backup.yml
Labels: urgent off-sprint issue

#4330 Add workaround docs for MemoryError during backup
  docs/backup_and_restore.rst
  docs/includes/backup-warning.txt
  docs/upgrade/xenial_backup_install_restore.rst
  docs/upgrade/xenial_prep.rst
Labels: docs, urgent off-sprint issue

#4333 [0.12.1] Add workaround docs for MemoryError during backup
  docs/backup_and_restore.rst
  docs/includes/backup-warning.txt
  docs/upgrade/xenial_backup_install_restore.rst
  docs/upgrade/xenial_prep.rst
Labels: docs, urgent off-sprint issue

#4337 Remove references to legacy Jenkins setup
  devops/jenkins/TorNightlyPipeline
Labels: small off-sprint PR

#4323 [docs] Instruct admin to look up latest Tails version for Xenial upgrade
  docs/upgrade/xenial_prep.rst
Labels: small off-sprint PR

#4340 Override level of apache error log in ossec config
  install_files/securedrop-ossec-server/var/ossec/rules/local_rules.xml
  molecule/testinfra/staging/vars/staging.yml
Labels: urgent off-sprint issue

#4348 [provisioning] cleanup now not needed trusty gettext install logic
  install_files/ansible-base/roles/app-test/tasks/modern_gettext.yml
Labels: small off-sprint PR

#4346 Update Jinja2 to 2.10.1, Ansible to 2.6.14 and SQLAlchemy to 1.3.0
  admin/requirements.txt
  install_files/ansible-base/callback_plugins/ansible_version_check.py
  securedrop/requirements/develop-requirements.txt
  securedrop/requirements/securedrop-app-code-requirements.in
  securedrop/requirements/securedrop-app-code-requirements.txt
  securedrop/requirements/test-requirements.txt
  securedrop/tests/test_journalist.py
Labels: urgent off-sprint issue

#4353 Fix Dockerfiles, create-dev-data
  securedrop/create-dev-data.py
  securedrop/dockerfiles/xenial/python2/Dockerfile
  securedrop/dockerfiles/xenial/python3/Dockerfile
Labels: small off-sprint PR

#4344 update qubes staging Makefile target to use Xenial by default
  devops/scripts/create-staging-env
  docs/development/qubes_staging.rst
  molecule/qubes-staging/qubes-vars.yml
Labels: small off-sprint PR

#4370 [docs] Fixes errors in landing page and onboarding documentation.
  docs/deployment/landing_page.rst
  docs/onboarding.rst
Labels: docs, small off-sprint PR

#4386 [docs] Add steps for creating GitHub release, notifying support portal to release process
  docs/development/release_management.rst
Labels: docs, small off-sprint PR

#4359 [docs] More detailed guide to investigating and enabling logs
  docs/admin.rst
  docs/includes/get-logs.txt
  docs/logging.rst
Labels: docs, small off-sprint PR

#4388 Run deb tests when updating builder image
  .circleci/config.yml
  Makefile
  devops/scripts/test-built-packages.sh
  docs/development/dockerbuildmaint.rst
Labels: small off-sprint PR

#4369 [docs] Clarified workstation hardware requirements
  docs/overview.rst
Labels: docs, small off-sprint PR
