Repository freedomofpress/securedrop, pull requests merged in 2019-07, with the labels that each got.

#4586 Update Admin Workstation setup instructions to use keys.openpgp.org
  docs/set_up_admin_tails.rst
Labels: docs

#4591 reduce failure rate of 2FA admin functional tests
  securedrop/tests/functional/functional_test.py
  securedrop/tests/functional/journalist_navigation_steps.py
Labels: small off-sprint PR

#4592 ci: export junit XML test metadata
  .circleci/config.yml
  .gitignore
  securedrop/bin/run-test
Labels: small off-sprint PR

#4636 CI: move fetch-tor-debs job to weekly
  .circleci/config.yml
Labels: small off-sprint PR

#4638 Update copyright dates
  docs/conf.py
Labels: small off-sprint PR

#4643 Eliminate Flask-SQLAlchemy deprecation warnings
  securedrop/models.py
  securedrop/requirements/python3/securedrop-app-code-requirements.txt
Labels: small off-sprint PR

#4651 Remove printer troubleshooting guide from 2015
  docs/images/printer_setup_guide/bad_test_page.png
  docs/images/printer_setup_guide/change_make_and_model.png
  docs/images/printer_setup_guide/driver_search_result_default_1.png
  docs/images/printer_setup_guide/driver_search_result_default_2.png
  docs/images/printer_setup_guide/driver_search_results_custom.png
  docs/images/printer_setup_guide/edit_properties.png
  docs/images/printer_setup_guide/good_test_page.png
  docs/images/printer_setup_guide/grant_admin.png
  docs/images/printer_setup_guide/path_to_printer_settings.png
  docs/images/printer_setup_guide/print_test_page.png
  docs/images/printer_setup_guide/printer_config_added.png
  docs/images/printer_setup_guide/printer_list.png
  docs/images/printer_setup_guide/save_printer_config.png
  docs/images/printer_setup_guide/searching_for_drivers.png
  docs/images/printer_setup_guide/select_printer.png
  docs/images/printer_setup_guide/tails_desktop_no_network.png
  docs/images/printer_setup_guide/unhappy_printer.png
  docs/tails_printing_guide.rst
Labels: docs, small off-sprint PR
