Repository freedomofpress/securedrop, pull requests merged in 2019-06, with the labels that each got.

#4476 [docs] Consolidate list of issues tags under one heading
  docs/development/contributing.rst
Labels: small off-sprint PR

#4496 Redirect to index after session expiration on /generate
  securedrop/source_app/__init__.py
  securedrop/tests/test_source.py
Labels: small off-sprint PR

#4497 Use archive module in `securedrop-admin logs` playbook
  install_files/ansible-base/securedrop-logs.yml
Labels: small off-sprint PR

#3274 Add explanatory text for authenticator reset buttons in Journalist/Admin interface
  securedrop/journalist_templates/edit_account.html
  securedrop/sass/_base.sass
  securedrop/sass/journalist.sass
  securedrop/sass/modules/_tooltip.sass
  securedrop/tests/functional/journalist_navigation_steps.py
  securedrop/tests/functional/test_admin_interface.py
Labels: goals: journalist experience, journalist_interface

#4512 Remove "now" from "SecureDrop now uses automatically generated .."
  securedrop/journalist_templates/edit_account.html
Labels: small off-sprint PR

#4487 Add make target to test docs for broken links
  .circleci/config.yml
  Makefile
  docs/conf.py
  docs/development/apt_repo.rst
  docs/development/contributing.rst
  docs/development/documentation_guidelines.rst
  docs/development/l10n.rst
  docs/development/testing_continuous_integration.rst
  docs/hardware.rst
  docs/includes/docs-branches.txt
  docs/network_firewall.rst
  docs/tails_guide.rst
Labels: small off-sprint PR

#4523 Fixes #4521 download journalist key via source interface
  securedrop/source_app/info.py
  securedrop/tests/functional/test_source.py
Labels: urgent off-sprint issue

#4548 Replace "Cloud" upload icon with more neutral one
  install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/files/usr.sbin.apache2
  securedrop/sass/source.sass
  securedrop/source_templates/index.html
  securedrop/source_templates/lookup.html
  securedrop/static/i/arrow-upload-blue.png
  securedrop/static/i/arrow-upload-large.png
  securedrop/static/i/arrow-upload-white.png
  securedrop/static/i/font-awesome/cloud-upload-blue-large.png
  securedrop/static/i/font-awesome/cloud-upload-blue.png
  securedrop/static/i/font-awesome/cloud-upload-white.png
Labels: small off-sprint PR
