Repository freedomofpress/securedrop, pull requests merged in 2019-08, with the labels that each got.

#4655 Remove unused tor_apt_repo_url override
  molecule/upgrade/ansible-override-vars.yml
Labels: small off-sprint PR

#4654 Assign unread checkbox class only to unread submissions
  securedrop/journalist_templates/col.html
Labels: small off-sprint PR

#4644 replace "hidden service" occurrences
  docs/configure_admin_workstation_post_install.rst
  docs/deployment/landing_page.rst
  docs/deployment/whole_site_changes.rst
  docs/hardware.rst
  docs/https_source_interface.rst
  docs/install.rst
  docs/journalist.rst
  docs/onboarding.rst
  docs/overview.rst
  docs/passphrase_best_practices.rst
  docs/passphrases.rst
  docs/rebuild_admin.rst
  docs/threat_model/mitigations.rst
  docs/training_schedule.rst
  install_files/ansible-base/group_vars/securedrop_application_server.yml
  install_files/ansible-base/group_vars/securedrop_monitor_server.yml
  install_files/ansible-base/inventory-dynamic
  install_files/ansible-base/roles/backup/files/0.3_collect.py
  install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/files/changelog-trusty
  install_files/ansible-base/roles/restrict-direct-access/tasks/fetch_tor_config.yml
  install_files/ansible-base/roles/restrict-direct-access/templates/rules_v4
  install_files/ansible-base/roles/tails-config/files/65-configure-tor-for-securedrop.sh
  install_files/ansible-base/roles/tor-hidden-services/tasks/configure_tor_hidden_services.yml
  molecule/testinfra/staging/app/test_tor_config.py
  molecule/testinfra/staging/app/test_tor_hidden_services.py
  molecule/vagrant-packager/side_effect.yml
  tails_files/torrc_additions
Labels: small off-sprint PR

#4673 Remove obsolete and redundant Tails Guide
  docs/index.rst
  docs/onboarding.rst
  docs/passphrases.rst
  docs/set_up_admin_tails.rst
  docs/tails_guide.rst
  docs/tails_printing_guide.rst
Labels: docs, small off-sprint PR

#4717 Adjust tooltip sizing/weight to reduce likelihood of abbreviation
  securedrop/sass/modules/_tooltip.sass
Labels: QA: Release
