Repository freedomofpress/securedrop, pull requests merged in 2020-09, with the labels that each got.

#5478 Add note on creating virtualenv and Fedora install docs
  docs/development/documentation_guidelines.rst
  docs/development/setup_development.rst
  docs/includes/virtualenv.txt
Labels: docs

#5487 Remove traces of obsolete dependences from virtualenv
  install_files/securedrop-app-code/debian/postinst
Labels: small off-sprint PR

#5538 Fix update_version.sh script
  update_version.sh
Labels: QA: Release, priority/high
