Repository freedomofpress/securedrop, pull requests merged in 2020-03, with the labels that each got.

#5133 Update pylint, astroid, mypy
  securedrop/requirements/python3/develop-requirements.in
  securedrop/requirements/python3/develop-requirements.txt
  securedrop/tests/functional/journalist_navigation_steps.py
Labels: development env, goals: improve developer workflow, small off-sprint PR

#5164 Add 1.2.1->1.2.2 upgrade guide
  docs/index.rst
  docs/upgrade/1.2.1_to_1.2.2.rst
Labels: docs

#5171 Ignore shellcheck warning 2230
  devops/scripts/boot-strap-venv.sh
  devops/scripts/match-ci-branch.sh
  devops/scripts/vnc-docker-connect.sh
  install_files/securedrop-keyring/DEBIAN/preinst
  update_version.sh
Labels: small off-sprint PR
