Repository freedomofpress/securedrop, pull requests merged in 2020-11, with the labels that each got.

#5614 Fix test_rm.py::test_secure_delete_capability
  securedrop/tests/test_rm.py
Labels: small off-sprint PR

#5616 Fix type hints in models, qa_loader
  securedrop/models.py
  securedrop/qa_loader.py
Labels: small off-sprint PR

#5618 Prevent IntegrityError on repeated reset of journalist password
  securedrop/journalist_app/utils.py
Labels: small off-sprint PR

#5628 Add missing static/icons directory to debian package
  securedrop/.rsync-filter
Labels: release blocker

#5644 Improve testing of static assets in Debian packaging
  molecule/builder-xenial/tests/conftest.py
  molecule/builder-xenial/tests/test_securedrop_deb_package.py
  molecule/builder-xenial/tests/testutils.py
  molecule/builder-xenial/tests/vars.yml
Labels: goals: more tests, off-sprint PR, tests
