Repository freedomofpress/securedrop, pull requests merged in 2020-07, with the labels that each got.

#5337 [docs] Qubes development documentation fixes
  docs/development/qubes_staging.rst
  docs/development/setup_development.rst
  docs/development/virtual_environments.rst
Labels: small off-sprint PR

#5357 Further redcation of wordlist
  securedrop/dictionaries/adjectives.txt
  securedrop/dictionaries/nouns.txt
Labels: small off-sprint PR

#5354 Document unsafe browser behavior in Tails 4.8
  docs/images/tails_4x/unsafe-browser.png
  docs/network_firewall.rst
  docs/set_up_admin_tails.rst
Labels: docs, small off-sprint PR

#5363 Remove an extra space after a period
  securedrop/journalist_templates/config.html
Labels: small off-sprint PR

#5396 Fix linkcheck GitHub 429 errors
  docs/conf.py
Labels: small off-sprint PR

#5432 Get CI parallelization of translation tests working again
  .circleci/config.yml
  Makefile
Labels: CI-specific bug, goals: sick CI, small off-sprint PR

#5430 Ensure the test config is valid
  Makefile
  securedrop/bin/dev-shell
Labels: development env, small off-sprint PR
