Repository freedomofpress/securedrop, pull requests merged in 2021-02, with the labels that each got.

#5771 Remove the cloud-init package during server installation
  install_files/ansible-base/roles/prepare-servers/tasks/main.yml
  molecule/testinfra/common/test_system_hardening.py
Labels: release blocker

#5774 Always update TorBrowser to the latest release
  securedrop/dockerfiles/focal/python3/Dockerfile
  securedrop/dockerfiles/xenial/python3/Dockerfile
Labels: small off-sprint PR

#5783 Update ossec service files to start after the local network is online
  install_files/ansible-base/roles/build-ossec-deb-pkg/files/ossec-agent.service
  install_files/ansible-base/roles/build-ossec-deb-pkg/files/ossec.service
Labels: release blocker

#5666 Update and add annotations to sshd config for servers
  install_files/ansible-base/roles/restrict-direct-access/templates/sshd_config
  molecule/testinfra/common/test_system_hardening.py
Labels: release blocker

#5780 Fixes #5776 adds iptables-persistent dependency on Focal
  install_files/ansible-base/roles/app/handlers/main.yml
  install_files/ansible-base/roles/common/vars/Ubuntu_focal.yml
  install_files/ansible-base/roles/restrict-direct-access/tasks/iptables.yml
  install_files/ansible-base/roles/restrict-direct-access/tasks/main.yml
  install_files/ansible-base/roles/restrict-direct-access/vars/Ubuntu_focal.yml
  install_files/ansible-base/roles/restrict-direct-access/vars/Ubuntu_xenial.yml
  molecule/testinfra/common/test_system_hardening.py
Labels: release blocker

#5790 Update translated strings
  securedrop/translations/messages.pot
Labels: i18n, small off-sprint PR

#5791 Reduce localization manager review noise
  install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
  install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
  securedrop/i18n_tool.py
  securedrop/translations/ar/LC_MESSAGES/messages.po
  securedrop/translations/ca/LC_MESSAGES/messages.po
  securedrop/translations/cs/LC_MESSAGES/messages.po
  securedrop/translations/de_DE/LC_MESSAGES/messages.po
  securedrop/translations/el/LC_MESSAGES/messages.po
  securedrop/translations/es_ES/LC_MESSAGES/messages.po
  securedrop/translations/fr_FR/LC_MESSAGES/messages.po
  securedrop/translations/hi/LC_MESSAGES/messages.po
  securedrop/translations/is/LC_MESSAGES/messages.po
  securedrop/translations/it_IT/LC_MESSAGES/messages.po
  securedrop/translations/messages.pot
  securedrop/translations/nb_NO/LC_MESSAGES/messages.po
  securedrop/translations/nl/LC_MESSAGES/messages.po
  securedrop/translations/pt_BR/LC_MESSAGES/messages.po
  securedrop/translations/ro/LC_MESSAGES/messages.po
  securedrop/translations/ru/LC_MESSAGES/messages.po
  securedrop/translations/sk/LC_MESSAGES/messages.po
  securedrop/translations/sv/LC_MESSAGES/messages.po
  securedrop/translations/tr/LC_MESSAGES/messages.po
  securedrop/translations/zh_Hans/LC_MESSAGES/messages.po
  securedrop/translations/zh_Hant/LC_MESSAGES/messages.po
Labels: goals: speed up release process, i18n

#5813 [Focal] Fix reboot-flag cron syntax
  install_files/securedrop-config-focal/opt/securedrop/reboot-flag
  molecule/testinfra/common/test_automatic_updates.py
Labels: QA: Release, release blocker

#5677 Disable v2 onion addresses on restore on Focal
  install_files/ansible-base/roles/restore/files/compare_torrc.py
  install_files/ansible-base/roles/restore/files/disable_v2.py
  install_files/ansible-base/roles/restore/tasks/main.yml
Labels: release blocker

#5810 Disables IPv6 via cmdline option for Focal
  install_files/ansible-base/group_vars/all/securedrop
  install_files/ansible-base/group_vars/securedrop_application_server.yml
  install_files/ansible-base/group_vars/securedrop_monitor_server.yml
  install_files/ansible-base/roles/common/defaults/main.yml
  install_files/ansible-base/roles/common/tasks/post_ubuntu_install_checks.yml
  install_files/ansible-base/roles/common/tasks/sysctl.yml
  install_files/ansible-base/roles/grsecurity/tasks/from_local_pkg_install_grsec.yml
  install_files/ansible-base/roles/install-local-packages/tasks/hold_debs.yml
  install_files/securedrop-grsec-focal/DEBIAN/postinst.j2
  molecule/testinfra/common/test_automatic_updates.py
  molecule/testinfra/common/test_grsecurity.py
  molecule/testinfra/common/test_ip6tables.py
  molecule/testinfra/common/test_system_hardening.py
Labels: release blocker

#5826 Normalize translator comments to correct them in Weblate
  securedrop/journalist_app/col.py
  securedrop/journalist_app/main.py
  securedrop/journalist_app/utils.py
Labels: i18n
