Repository freedomofpress/securedrop, pull requests merged in 2022-11, with the labels that each got.

#6666 Automatically change respective SELinux contexts when running containers
  admin/bin/dev-shell
  devops/scripts/shellcheck.sh
  securedrop/bin/dev-shell
Labels: hackathon2022: prep

#6674 fix: determine and add `safe.directory` entry for `$REPOROOT` directly from the filesystem
  securedrop/bin/run
Labels: development env, hackathon2022: prep

#6675 Make container compatible with Apple Silicon
  securedrop/bin/dev-shell
Labels: development env, hackathon2022: prep

#6683 Configure hooks when running `make venv`
  .githooks/pre-commit
  Makefile
Labels: development env
