Repository freedomofpress/securedrop, pull requests merged in 2023-10, with the labels that each got.

#6964 Import Markup and escape from markupsafe
  securedrop/journalist_app/col.py
  securedrop/journalist_app/main.py
  securedrop/journalist_app/utils.py
Labels: small off-sprint PR

#6971 Point mypy at redwood type stub directly
  redwood/redwood/__init__.pyi
  securedrop/bin/run-mypy
Labels: goals: sick CI

#6961 Replace bandit with ruff
  .circleci/config.yml
  Makefile
  devops/scripts/verify-mo.py
  pyproject.toml
  securedrop/alembic/versions/2e24fc7536e8_make_journalist_id_non_nullable.py
  securedrop/alembic/versions/3da3fcab826a_delete_orphaned_submissions.py
  securedrop/alembic/versions/b7f98cfd6a70_make_filesystem_id_non_nullable.py
  securedrop/journalist.py
  securedrop/models.py
  securedrop/pretty_bad_protocol/_util.py
  securedrop/request_that_secures_file_uploads.py
  securedrop/requirements/python3/develop-requirements.in
  securedrop/requirements/python3/develop-requirements.txt
  securedrop/source.py
  securedrop/store.py
  securedrop/tests/migrations/migration_de00920916bf.py
  securedrop/two_factor.py
Labels: goals: sick CI

#7014 Do not include config.py in built packages
  securedrop/debian/rules
Labels: small off-sprint PR

#7021 Wordlist removals
  securedrop/dictionaries/adjectives.txt
  securedrop/dictionaries/nouns.txt
Labels: small off-sprint PR

#7034 build(`extract-strings`): don't version gettext templates
  Makefile
  install_files/ansible-base/roles/tails-config/templates/locale/messages.pot
  securedrop/translations/messages.pot
Labels: i18n

#7052 Have CI verify demo container builds and runs
  .github/workflows/demo.yml
Labels: goals: sick CI
