Repository freedomofpress/securedrop, pull requests merged in 2023-06, with the labels that each got.

#6768 Replace Cross-Origin-Resource-Policy: 'same-site' with 'same-origin'
  install_files/ansible-base/roles/app/templates/sites-available/focal/journalist.conf
  install_files/ansible-base/roles/app/templates/sites-available/focal/source.conf
  molecule/testinfra/vars/app-qubes-staging.yml
  molecule/testinfra/vars/app-staging.yml
  molecule/testinfra/vars/prod.yml
  molecule/testinfra/vars/prodVM.yml
  molecule/testinfra/vars/qubes-staging.yml
  molecule/testinfra/vars/staging.yml
  securedrop/debian/securedrop-app-code.postinst
Labels: release stretch goal

#6834 Remove Debian autogenerated conffiles from securedrop-keyring
  securedrop/debian/rules
Labels: goals: packaging

#6832 Update Rust in builder to 1.69.0
  builder/Dockerfile
  builder/build-debs-securedrop.sh
Labels: Rust

#6844 Use cargo's sparse index in Rust CI too
  .circleci/config.yml
Labels: Rust

#6854 test: `s/Login/Log in/` hard-coded in tests
  securedrop/tests/functional/app_navigators/journalist_app_nav.py
  securedrop/tests/i18n/securedrop/translations/de_DE/LC_MESSAGES/messages.po
  securedrop/tests/i18n/securedrop/translations/nl/LC_MESSAGES/messages.po
  securedrop/tests/test_journalist.py
Labels: QA: Release
