Repository freedomofpress/securedrop, pull requests merged in 2023-08, with the labels that each got.

#6912 Add tests for empty or malformed recipient gpg key
  redwood/src/lib.rs
Labels: Rust

#6923 ci: run all non-staging tests on `i18n-` branches
  .circleci/config.yml
Labels: i18n

#6929 chore: add the "silencing an alert" case to the checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small off-sprint PR
