Repository freedomofpress/securedrop, pull requests merged in 2024-11, with the labels that each got.

#7303 Don't install apt-transport-https, it's an unnecessary transitional package
  install_files/ansible-base/roles/common/vars/Ubuntu_focal.yml
  install_files/ansible-base/roles/prepare-servers/tasks/main.yml
Labels: noble

#7307 Overwrite sources.list.d/ubuntu.sources on noble
  install_files/ansible-base/roles/common/tasks/apt_sources.yml
  install_files/ansible-base/roles/common/templates/ubuntu.sources.j2
  molecule/testinfra/common/test_automatic_updates.py
Labels: noble

#7305 Remove test_securedrop_application_apt_dependencies test
  molecule/testinfra/app-code/test_securedrop_app_code.py
  molecule/testinfra/conftest.py
  molecule/testinfra/mon/test_ossec_server.py
Labels: noble

#7319 Have app-code depend on apparmor in noble
  builder/tests/test_securedrop_deb_package.py
  securedrop/debian/control
  securedrop/debian/rules
Labels: noble

#7315 Remove ufw from new and existing installs
  install_files/ansible-base/roles/prepare-servers/tasks/main.yml
  molecule/testinfra/common/test_system_hardening.py
  securedrop/debian/config/lib/systemd/system/securedrop-remove-packages.service
  securedrop/debian/config/lib/systemd/system/securedrop-remove-packages.timer
  securedrop/debian/rules
  securedrop/debian/securedrop-config.install
Labels: noble

#7317 Don't reuse the "ssh" group for our own access control
  install_files/ansible-base/roles/common/tasks/create_users.yml
  install_files/ansible-base/roles/restrict-direct-access/templates/rules_v4
  install_files/ansible-base/roles/restrict-direct-access/templates/sshd_config
  molecule/testinfra/app/test_app_network.py
  molecule/testinfra/common/test_system_hardening.py
  molecule/testinfra/mon/test_mon_network.py
  securedrop/debian/config/usr/bin/securedrop-migrate-ssh-group.py
  securedrop/debian/securedrop-config.install
  securedrop/debian/securedrop-config.postinst
Labels: noble

#7308 Remove tests checking that no apparmor profiles are complaining
  molecule/testinfra/app/test_apparmor.py
  molecule/testinfra/vars/app-prod.yml
  molecule/testinfra/vars/app-qubes-staging.yml
  molecule/testinfra/vars/app-staging.yml
  molecule/testinfra/vars/prod.yml
  molecule/testinfra/vars/prodVM.yml
  molecule/testinfra/vars/qubes-staging.yml
  molecule/testinfra/vars/staging.yml
Labels: noble

#7306 Expand some testinfra checks to expect noble
  molecule/testinfra/common/test_automatic_updates.py
  molecule/testinfra/common/test_platform.py
Labels: noble

#7336 Actually enable systemd timers in securedrop-config package
  securedrop/debian/securedrop-config.postinst
Labels: noble

#7335 Remove haveged if installed
  securedrop/debian/config/lib/systemd/system/securedrop-remove-packages.service
  securedrop/debian/securedrop-app-code.preinst
Labels: noble

#7341 Update securedrop-remove-packages.timer description
  securedrop/debian/config/lib/systemd/system/securedrop-remove-packages.timer
Labels: noble

#7331 Install backup script on app server via Debian package
  install_files/ansible-base/roles/backup/tasks/backup.yml
  molecule/testinfra/app/test_backup.py
  securedrop/debian/app-code/usr/bin/securedrop-app-backup.py
  securedrop/debian/securedrop-app-code.install
Labels: noble

#7337 Replace reboot-flag cron job with a systemd timer
  molecule/testinfra/common/test_automatic_updates.py
  securedrop/debian/config/lib/systemd/system/securedrop-reboot-required.service
  securedrop/debian/config/lib/systemd/system/securedrop-reboot-required.timer
  securedrop/debian/rules
  securedrop/debian/securedrop-config.postinst
Labels: noble

#7260 feat: make `backport.py` more flexible for complex pull requests
  utils/backport.py
Labels: goals: improve developer workflow

#7324 Drop setting vm.heap_stack_gap and net.ipv4 sysctl flags
  install_files/ansible-base/roles/common/defaults/main.yml
  install_files/ansible-base/roles/common/tasks/main.yml
  install_files/ansible-base/roles/common/tasks/sysctl.yml
  install_files/ansible-base/roles/grsecurity/defaults/main.yml
  molecule/testinfra/common/test_grsecurity.py
  molecule/testinfra/common/test_system_hardening.py
Labels: blocked, noble

#7342 Absent sources.list on noble
  install_files/ansible-base/roles/common/tasks/apt_sources.yml
Labels: noble

#7353 Only try to apply grsec_lock once
  install_files/ansible-base/roles/grsecurity/tasks/apply_grsec_lock.yml
Labels: noble

#7240 ci(translation): save screenshots as workflow artifacts
  .github/workflows/translation.yml
  Makefile
  securedrop/bin/dev-config
  securedrop/i18n.json
  securedrop/i18n.rst
  securedrop/tests/functional/app_navigators/journalist_app_nav.py
  securedrop/tests/functional/app_navigators/source_app_nav.py
  securedrop/tests/functional/conftest.py
  securedrop/tests/functional/pageslayout/test_journalist.py
  securedrop/tests/functional/pageslayout/test_journalist_account.py
  securedrop/tests/functional/pageslayout/test_journalist_admin.py
  securedrop/tests/functional/pageslayout/test_journalist_col.py
  securedrop/tests/functional/pageslayout/test_journalist_delete.py
  securedrop/tests/functional/pageslayout/test_source.py
  securedrop/tests/functional/pageslayout/test_source_layout_torbrowser.py
  securedrop/tests/functional/pageslayout/test_source_session_layout.py
  securedrop/tests/functional/pageslayout/test_source_static_pages.py
  securedrop/tests/functional/pageslayout/test_submit_and_retrieve_file.py
  securedrop/tests/functional/web_drivers.py
Labels: i18n, goals: sick CI

#7357 Fix typo of securedrop-reboot-required unit in testinfra tests
  molecule/testinfra/common/test_automatic_updates.py
Labels: noble
