Repository freedomofpress/securedrop, pull requests merged in 2024-12, with the labels that each got.

#7348 Display a banner in the JI regarding the noble migration
  Makefile
  securedrop/journalist_app/__init__.py
  securedrop/journalist_templates/base.html
  securedrop/server_os.py
  securedrop/source_app/__init__.py
  securedrop/tests/test_journalist.py
  securedrop/translations/messages.pot
Labels: noble

#7363 Fix free space check by measuring bytes, not kilobytes
  noble-migration/src/bin/check.rs
Labels: noble

#7370 chore: address feedback on source strings
  securedrop/journalist_templates/base.html
  securedrop/journalist_templates/index.html
  securedrop/source_templates/tor2web-warning.html
  securedrop/tests/test_integration.py
  securedrop/tests/test_journalist.py
  securedrop/translations/messages.pot
Labels: i18n

#7369 Improve noble migration check script output
  noble-migration/src/bin/check.rs
Labels: noble

#7375 refine `backport.py`
  utils/backport.py
Labels: goals: improve developer workflow

#7387 chore: grant support to Croatian (`hr`)
  install_files/ansible-base/roles/tails-config/templates/desktop-journalist-icon.j2
  install_files/ansible-base/roles/tails-config/templates/desktop-source-icon.j2
  install_files/ansible-base/roles/tails-config/templates/locale/LINGUAS
  securedrop/i18n.json
  securedrop/i18n.rst
Labels: i18n

#7397 chore: remove Git `.mailmap`
  .mailmap
Labels: i18n

#7272 Have securedrop-admin emit distinct error messages
  admin/securedrop_admin/__init__.py
  admin/tests/test_integration.py
  admin/tests/test_securedrop-admin.py
Labels: needs/response
